### Exercise 1: Line Plot Customization

In [1]:
# TASK: Create a line plot with x values ranging from 0 to 10 and y values as the square of x.
# Customize the plot by adding a title, labels for both axes, and a grid.
import numpy as np

def main():
    # Task 1: Generate 5x5 matrix with random numbers (0-1) using fixed seed
    np.random.seed(42)  # Fixed seed for reproducibility
    matrix = np.random.rand(5, 5)
    
    print("Generated 5x5 Matrix:")
    print(np.round(matrix, 2))
    print("\n")
    
    # Task 2: Invert Matrix with error handling
    try:
        inv_matrix = np.linalg.inv(matrix)
        print("Inverse Matrix:")
        print(np.round(inv_matrix, 2))
        print("\n")
        
        # Task 3: Verify Identity
        identity_product = np.matmul(matrix, inv_matrix)
        identity_check = np.allclose(identity_product, np.eye(5), atol=1e-8)
        
        print("Matrix × Inverse (should be close to identity):")
        print(np.round(identity_product, 2))
        print(f"\nIs product close to identity matrix? {identity_check}")
        print("\n")
        
    except np.linalg.LinAlgError:
        print("Error: Matrix is singular and cannot be inverted.")
        print("\n")
    
    # Task 4: Statistical Analysis of original matrix
    print("Statistical Analysis of Original Matrix:")
    print(f"Mean: {np.mean(matrix):.2f}")
    print(f"Median: {np.median(matrix):.2f}")
    print(f"Variance: {np.var(matrix):.2f}")

if __name__ == "__main__":
    main()

Generated 5x5 Matrix:
[[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]


Inverse Matrix:
[[  364.6    334.17   -91.42  -895.55   -35.23]
 [ -351.87  -323.94    89.08   864.21    35.93]
 [  584.81   538.01  -146.16 -1436.9    -59.52]
 [ -234.81  -217.08    57.15   582.67    22.5 ]
 [ -567.51  -519.48   143.12  1389.49    58.52]]


Matrix × Inverse (should be close to identity):
[[ 1.  0. -0.  0.  0.]
 [-0.  1.  0.  0. -0.]
 [ 0.  0.  1.  0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0.  0. -0. -0.  1.]]

Is product close to identity matrix? True


Statistical Analysis of Original Matrix:
Mean: 0.44
Median: 0.37
Variance: 0.08
